#!/bin/bash
echo "=== Final Project Structure Verification ==="
echo ""
echo "📁 Backend Components:"
echo "  ✓ Core: $(ls -1 backend/app/core/*.py 2>/dev/null | wc -l) files"
echo "  ✓ API: $(ls -1 backend/app/api/*.py 2>/dev/null | wc -l) files"
echo "  ✓ Models: $(ls -1 backend/app/models/*.py 2>/dev/null | wc -l) files"
echo "  ✓ Schemas: $(ls -1 backend/app/schemas/*.py 2>/dev/null | wc -l) files"
echo "  ✓ Services: $(ls -1 backend/app/services/*.py 2>/dev/null | wc -l) files"
echo "  ✓ Tasks: $(ls -1 backend/app/tasks/*.py 2>/dev/null | wc -l) files"
echo "  ✓ Worker: $(ls -1 backend/app/worker.py 2>/dev/null | wc -l) file"
echo ""
echo "📁 Frontend Components:"
echo "  ✓ Components: $(ls -1 frontend/src/components/*.tsx 2>/dev/null | wc -l) files"
echo "  ✓ Pages: $(ls -1 frontend/src/pages/*.tsx 2>/dev/null | wc -l) files"
echo "  ✓ Utils: $(ls -1 frontend/src/utils/*.ts 2>/dev/null | wc -l) files"
echo "  ✓ Types: $(ls -1 frontend/src/types/*.ts 2>/dev/null | wc -l) files"
echo ""
echo "📁 Configuration Files:"
[ -f .env.example ] && echo "  ✓ .env.example"
[ -f docker-compose.yml ] && echo "  ✓ docker-compose.yml"
[ -f backend/Dockerfile ] && echo "  ✓ backend/Dockerfile"
[ -f frontend/Dockerfile ] && echo "  ✓ frontend/Dockerfile"
[ -f backend/requirements.txt ] && echo "  ✓ backend/requirements.txt"
[ -f frontend/package.json ] && echo "  ✓ frontend/package.json"
echo ""
echo "📁 Documentation:"
[ -f README.md ] && echo "  ✓ README.md"
[ -f ARCHITECTURE.md ] && echo "  ✓ ARCHITECTURE.md"
[ -f DEMO.md ] && echo "  ✓ DEMO.md"
[ -f IMPLEMENTATION_SUMMARY.md ] && echo "  ✓ IMPLEMENTATION_SUMMARY.md"
echo ""
echo "📊 API Endpoints:"
grep "@router\." backend/app/api/routes.py | grep -oP '(get|post|put|delete)\("[^"]*"' | sed 's/"//' | sed 's/^/  ✓ /'
echo ""
echo "✅ All components successfully implemented!"
echo ""
echo "🚀 Ready to start:"
echo "   docker-compose up --build"
